# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Addcity.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import json


class AddCity(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(522, 515)
        Dialog.setStyleSheet("background-color: #cccccc;\n"
"border-left: 4px solid #0A1172;\n"
"border-right: 4px solid #0A1172;\n"
"border-bottom: 4px solid #0A1172;\n"
"border-top:4px solid #0A1172;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 50, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none;\n"
"color: #0a1172;\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0a1172;")
        self.label_2.setObjectName("label_2")
        self.cityname = QtWidgets.QLineEdit(Dialog)
        self.cityname.setGeometry(QtCore.QRect(250, 130, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cityname.setFont(font)
        self.cityname.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172;\n"
"")
        self.cityname.setText("")
        self.cityname.setObjectName("cityname")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 210, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0a1172;")
        self.label_3.setObjectName("label_3")
        self.latitude = QtWidgets.QLineEdit(Dialog)
        self.latitude.setGeometry(QtCore.QRect(250, 200, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.latitude.setFont(font)
        self.latitude.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172;\n"
"")
        self.latitude.setText("")
        self.latitude.setObjectName("latitude")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 280, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0a1172;")
        self.label_4.setObjectName("label_4")
        self.longitude = QtWidgets.QLineEdit(Dialog)
        self.longitude.setGeometry(QtCore.QRect(250, 270, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.longitude.setFont(font)
        self.longitude.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172;\n"
"")
        self.longitude.setText("")
        self.longitude.setObjectName("longitude")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 360, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0a1172;")
        self.label_6.setObjectName("label_6")
        self.adjacentDistricts = QtWidgets.QLineEdit(Dialog)
        self.adjacentDistricts.setGeometry(QtCore.QRect(250, 350, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adjacentDistricts.setFont(font)
        self.adjacentDistricts.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172;\n"
"")
        self.adjacentDistricts.setText("")
        self.adjacentDistricts.setObjectName("adjacentDistricts")
        self.addcity = QtWidgets.QPushButton(Dialog)
        self.addcity.setGeometry(QtCore.QRect(360, 430, 121, 51))
        self.addcity.setStyleSheet("padding: 5px;\n"
"background-color: #0A1172;\n"
"color: white;")
        self.addcity.setObjectName("addcity")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.addcity.clicked.connect(self.save_city_details)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Add new City"))
        self.label_2.setText(_translate("Dialog", "City name:"))
        self.label_3.setText(_translate("Dialog", "Latitude:"))
        self.label_4.setText(_translate("Dialog", "Longitude:"))
        self.label_6.setText(_translate("Dialog", "Adjacent Districts:"))
        self.addcity.setText(_translate("Dialog", "Add City"))

    def save_city_details(self):
        city_name = self.cityname.text()
        city_latitude = float(self.latitude.text())
        city_longitude = float(self.longitude.text())
        adjacent_districts = self.adjacentDistricts.text().split(',')

        try:
            with open('data.txt', 'r') as file:
                city_data = json.load(file)
        except FileNotFoundError:
            city_data = {}

        city_data[city_name] = {
            "coordinates": {
                "latitude": city_latitude,
                "longitude": city_longitude
            },
            "adjacent_districts": [district.strip() for district in adjacent_districts]
        }

        with open('data.txt', 'w') as file:
            json.dump(city_data, file, indent=2)

        QtWidgets.QMessageBox.information(None, "City Added", f"{city_name} added successfully!")

        self.cityname.clear()
        self.latitude.clear()
        self.longitude.clear()
        self.adjacentDistricts.clear()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = AddCity()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

