# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import csv
import sys

class addUser(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(602, 402)
        Dialog.setStyleSheet("background-color: #cccccc;\n"
"border-left: 4px solid #0A1172;\n"
"border-right: 4px solid #0A1172;\n"
"border-bottom: 4px solid #0A1172;")
        self.passwordText = QtWidgets.QLineEdit(Dialog)
        self.passwordText.setGeometry(QtCore.QRect(310, 200, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordText.setFont(font)
        self.passwordText.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172;\n"
"")
        self.passwordText.setObjectName("passwordText")
        self.passwordText.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password = QtWidgets.QLabel(Dialog)
        self.password.setGeometry(QtCore.QRect(100, 200, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password.setFont(font)
        self.password.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172;")
        self.password.setObjectName("password")
        
        self.emailText = QtWidgets.QLineEdit(Dialog)
        self.emailText.setGeometry(QtCore.QRect(310, 140, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.emailText.setFont(font)
        self.emailText.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172;\n"
"")
        self.emailText.setObjectName("emailText")
        self.username = QtWidgets.QLabel(Dialog)
        self.username.setGeometry(QtCore.QRect(100, 80, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.username.setFont(font)
        self.username.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172;")
        self.username.setObjectName("username")
        self.usernameText = QtWidgets.QLineEdit(Dialog)
        self.usernameText.setGeometry(QtCore.QRect(310, 80, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usernameText.setFont(font)
        self.usernameText.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172;\n"
"")
        self.usernameText.setText("")
        self.usernameText.setObjectName("usernameText")
        self.email = QtWidgets.QLabel(Dialog)
        self.email.setGeometry(QtCore.QRect(100, 140, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.email.setFont(font)
        self.email.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172")
        self.email.setObjectName("email")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(240, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none;\n"
"color: #0a1172;\n"
"")
        self.label.setObjectName("label")
        self.password_2 = QtWidgets.QLabel(Dialog)
        self.password_2.setGeometry(QtCore.QRect(100, 260, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password_2.setFont(font)
        self.password_2.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172;")
        self.password_2.setObjectName("password_2")
        self.addUser = QtWidgets.QPushButton(Dialog)
        self.addUser.setGeometry(QtCore.QRect(450, 330, 121, 51))
        self.addUser.setStyleSheet("padding: 5px;\n"
"background-color: #0A1172;\n"
"color: white;")
        self.addUser.setObjectName("addUser")
        self.role = QtWidgets.QComboBox(Dialog)
        self.role.setGeometry(QtCore.QRect(310, 270, 191, 22))
        self.role.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172;\n"
"")
        self.role.setObjectName("role")
        self.role.addItem("")
        self.role.addItem("")
        self.role.addItem("")
        self.addUser.clicked.connect(self.__signUp)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def __signUp(self):
        usernameText = self.usernameText.text()
        passwordText = self.passwordText.text()
        emailText = self.emailText.text()
        if self.__register(usernameText, emailText, passwordText):
            self.__writeToCsv(usernameText, passwordText, emailText)
            QtWidgets.QMessageBox.warning(None, "Message", "User added successfully!")
            self.clearText()
           
        else:
            self.clearText()

    def clearText(self):
        self.emailText.clear()
        self.usernameText.clear()
        self.passwordText.clear()

    def __writeToCsv(self, usernameText, passwordText, emailText):
        with open('users.csv', mode='a', newline='') as file:
            writer = csv.writer(file)
            encrypted_password = self.__encryption(passwordText, 3)
            encrypted_email = self.__encryption(emailText, 3)
            role = self.role.currentText()  # Fetch the selected role from the combo box
            writer.writerow([usernameText, encrypted_password, encrypted_email, role])

    def __encryption(self, text, shift):
        encrypted_text = ""
        for char in text:
            shifted = ord(char) + (shift % 26)
            if char.isalpha():
                if char.islower():
                    if shifted > ord('z'):
                        shifted -= 26
                    elif shifted < ord('a'):
                        shifted += 26
                    encrypted_text += chr(shifted)
                elif char.isupper():
                    if shifted > ord('Z'):
                        shifted -= 26
                    elif shifted < ord('A'):
                        shifted += 26
                    encrypted_text += chr(shifted)
            elif char.isnumeric():
                if shifted > ord('9'):
                    shifted -= 10
                elif shifted < ord('0'):
                    shifted += 10
                encrypted_text += chr(shifted)
            else:
                encrypted_text += char
        return encrypted_text
    
    def __register(self,usernameText,emailText,passwordText):
        if not usernameText or not emailText or not passwordText:
            QMessageBox.warning(None, "Registration Error", "Please fill in all the required fields.")
            return False
        if not self.__isValid(emailText):
            QMessageBox.warning(None, "Registration Error", "Invalid email address. Please enter a valid email address.")
            return  False
        return True
    
    def __isValid(self, email):
            return '@' in email

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.password.setText(_translate("Dialog", "Password"))
        self.username.setText(_translate("Dialog", "Username"))
        self.email.setText(_translate("Dialog", "Email"))
        self.label.setText(_translate("Dialog", "Add User"))
        self.password_2.setText(_translate("Dialog", "Role"))
        self.addUser.setText(_translate("Dialog", "Add"))
        self.role.setItemText(0, _translate("Dialog", "-- Select Role --"))
        self.role.setItemText(1, _translate("Dialog", "Admin"))
        self.role.setItemText(2, _translate("Dialog", "User"))

	

class AddUserWindow(QtWidgets.QDialog, addUser):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        

def main():
    app = QtWidgets.QApplication(sys.argv)
    addUserWindow = AddUserWindow()
    addUserWindow.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
