# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Removecity.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(519, 247)
        Dialog.setStyleSheet("background-color: #cccccc;\n"
"border-left: 4px solid #0A1172;\n"
"border-right: 4px solid #0A1172;\n"
"border-bottom: 4px solid #0A1172;\n"
"border-top:4px solid #0A1172;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 40, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none;\n"
"color: #0a1172;\n"
"")
        self.label.setObjectName("label")
        self.cityname = QtWidgets.QLineEdit(Dialog)
        self.cityname.setGeometry(QtCore.QRect(260, 100, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cityname.setFont(font)
        self.cityname.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0A1172;\n"
"")
        self.cityname.setText("")
        self.cityname.setObjectName("cityname")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #0a1172;")
        self.label_2.setObjectName("label_2")
        self.Removebtn = QtWidgets.QPushButton(Dialog)
        self.Removebtn.setGeometry(QtCore.QRect(340, 170, 121, 51))
        self.Removebtn.setStyleSheet("padding: 5px;\n"
"background-color: #0A1172;\n"
"color: white;")
        self.Removebtn.setObjectName("Removebtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.Removebtn.clicked.connect(self.remove_city)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Remove City"))
        self.label_2.setText(_translate("Dialog", "City name:"))
        self.Removebtn.setText(_translate("Dialog", "Remove"))

class RemoveCityWindow(QtWidgets.QDialog, Ui_Dialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def remove_city(self):
        city_name = self.cityname.text().strip()

        with open('data.txt', 'r') as file:
            data = json.load(file)

        if city_name in data:
            for city, info in data.items():
                if city != city_name and city_name in info['adjacent_districts']:
                    info['adjacent_districts'].remove(city_name)

            del data[city_name]

            with open('data.txt', 'w') as file:
                json.dump(data, file, indent=2)
            
            print(f"{city_name} has been removed.")
        else:
            print(f"{city_name} does not exist in the data.")

        self.cityname.clear()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    remove_city_window = RemoveCityWindow()
    remove_city_window.show()
    sys.exit(app.exec_())