# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import csv

class Ui_Dialog_2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 461)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 471, 461))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 471, 81))
        self.frame_2.setStyleSheet("background-color:#993300;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 10, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#fff;")
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(200, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:#fff;")
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(120, 100, 271, 41))
        font = QtGui.QFont()
        font.setFamily("CentSchbkCyrill BT")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#993300;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#993300;")
        self.label_4.setObjectName("label_4")
        self.username = QtWidgets.QLineEdit(self.frame)
        self.username.setGeometry(QtCore.QRect(150, 170, 251, 31))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(150, 240, 251, 31))
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 240, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#993300;")
        self.label_5.setObjectName("label_5")
        self.email = QtWidgets.QLineEdit(self.frame)
        self.email.setGeometry(QtCore.QRect(150, 310, 251, 31))
        self.email.setText("")
        self.email.setObjectName("email")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(70, 310, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:#993300;")
        self.label_6.setObjectName("label_6")
        self.SignInButton = QtWidgets.QPushButton(self.frame)
        self.SignInButton.setGeometry(QtCore.QRect(150, 380, 251, 31))
        self.SignInButton.setStyleSheet("background-color:#993300;\n"
"color:#fff")
        self.SignInButton.setObjectName("SignInButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", " Route Optimization and Management"))
        self.label_7.setText(_translate("Dialog", "System"))
        self.label_3.setText(_translate("Dialog", "Create Account"))
        self.label_4.setText(_translate("Dialog", "Username:"))
        self.label_5.setText(_translate("Dialog", "Password:"))
        self.label_6.setText(_translate("Dialog", "Email:"))
        self.SignInButton.setText(_translate("Dialog", "SignUp"))

def encryption(text, shift):
    encrypted_text = ""
    for char in text:
        shifted = ord(char) + (shift % 26)
        if char.isalpha():
            if char.islower():
                if shifted > ord('z'):
                    shifted -= 26
                elif shifted < ord('a'):
                    shifted += 26
                encrypted_text += chr(shifted)
            elif char.isupper():
                if shifted > ord('Z'):
                    shifted -= 26
                elif shifted < ord('A'):
                    shifted += 26
                encrypted_text += chr(shifted)
        elif char.isnumeric():
            if shifted > ord('9'):
                shifted -= 10
            elif shifted < ord('0'):
                shifted += 10
            encrypted_text += chr(shifted)
        else:
            encrypted_text += char
    return encrypted_text


def write_to_csv(username, password, email):
    with open('users.csv', mode='a', newline='') as file:
        writer = csv.writer(file)
        encrypted_password = encryption(password, 3)
        encrypted_email = encryption(email, 3) 
        writer.writerow([username, encrypted_password, encrypted_email])

class SignUpDialog(QtWidgets.QDialog, Ui_Dialog_2):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.SignInButton.clicked.connect(self.sign_up)

    def sign_up(self):
        username = self.username.text()
        password = self.password.text()
        email = self.email.text()
        write_to_csv(username, password, email)
        print("Account created successfully!")
        self.close()


def main():
    app = QtWidgets.QApplication([])
    sign_in_dialog = SignUpDialog()
    sign_in_dialog.show()
    app.exec_()

if __name__ == "__main__":
    main()